# Generated by Django 3.2.9 on 2022-12-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.CharField(default='TITLE', max_length=50),
        ),
    ]
