# Generated by Django 4.1.2 on 2023-11-16 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastseen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
