# Generated by Django 4.1.2 on 2023-12-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
