# Generated by Django 4.2 on 2024-12-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("standard", "Standard User"),
                    ("privilaged", "Privilged User"),
                    ("admin", "Administrator"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
