# Generated by Django 3.2.9 on 2022-12-06 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221206_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announce',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
